"""
Generated configuration for the Behringer - PROVS-MINI
"""

import nallely


class OscillatorSection(nallely.Module):
    voice_A_wave = nallely.ModuleParameter(
        24,
        accepted_values=[
            "Twang",
            "Clav",
            "Xylophone",
            "Slippery Slope",
            "Enharmonic Square",
            "Xylogphone 2",
            "Mellow Square",
            "Chaos 1",
            "Chaos 2",
            "Chaos 3",
            "Chaos 4",
            "Bright Square",
            "Hollow",
            "BP Square",
            "Ski Slope",
            "Rasp",
            "Peal",
            "Fuzz",
            "Floss",
            "Excite",
            "Awaken",
            "Energize",
            "BP Twang",
            "Complex Pulse",
            "Mellow Square 2",
            "Harmonic Square",
            "Thin Ramp",
            "Xylophone 3",
            "Thin Square",
            "Harmonic Ramp",
            "Rouse",
            "Waken",
            "Sine",
            "Sawtooth",
            "Square",
            "Dome 1",
            "Dome 2",
            "Mellow Dome",
            "Dome 3",
            "Dome 4",
            "Rasp1",
            "Rasp 2",
            "Rasp 3",
            "Rasp 4",
            "Dome 5",
            "HP Saw",
            "High BP Saw",
            "High BP Square",
            "Vocal",
            "Squeeze Box",
            "Pulse",
            "Limp Saw",
            "Spark Wave 1",
            "Spark Wave 2",
            "Spark Wave 3",
            "Mid Wave 1",
            "Cacophonous Buzz 1",
            "Mid Buzz 1",
            "Dome 6",
            "Soft Dome 3",
            "Dome 7",
            "Spark Wave 4",
            "Spark Wave 5",
            "Soft Dome 4",
            "Dome 8",
            "Organ",
            "Spark Wave 6",
            "Soft Wave 1",
            "Soft Wave 2",
            "Spark Wave 7",
            "Reed",
            "Soft Wave 3",
            "Soft Wave 4",
            "Saxophone",
            "Soft Wave 5",
            "Trashy Wave 1",
            "Trashy Wave 2",
            "Trashy Wave 3",
            "Trashy Wave 4",
            "Trashy Wave 5",
            "Trashy Wave 6",
            "Jaw Harp 1",
            "Jaw Harp 2",
            "Soft Wave 6",
            "Thin 1",
            "Thin 2",
            "Spark Wave 8",
            "Spark Wave 9",
            "Spark Wave 10",
            "Soft Dome 5",
            "Soft Dome 6",
            "Cacophonous Buzz 2",
            "Thin 3",
            "Spark Wave 11",
            "Soft Dome 7",
            "Soft Wave 7",
            "Sine 2",
            "Sync'd Sine",
            "Thrashy Wave 7",
            "Twingle Pad",
            "Dome 9",
            "Thin 4",
            "Thin 5",
            "Thrashy Wave 8",
            "Thrashy Wave 9",
            "Thrashy Wave 10",
            "Thrashy Wave 11",
            "Thrashy Wave 12",
            "Thrashy Wave 13",
            "Spark Wave 12",
            "Spark Wave 13",
            "Thrashy Wave 14",
            "Thrashy Wave 15",
            "Rainbow",
            "Soft Dome 8",
            "Trashy Wave 16",
            "Soothing 1",
            "Soothing 2",
            "Space Wave",
            "5th Rasp",
            "Octave Wave",
            "Triangle + Overtones",
            "Pulse + Overtones",
            "Rising Square",
            "Soft Wave 8",
            "Cacophonous Buzz 3",
            "Silence",
            "White Noise",
        ],
    )
    voice_A_coarse_tuning = nallely.ModuleParameter(115)
    voice_A_fine_tuning = nallely.ModuleParameter(111)
    voice_B_wave = nallely.ModuleParameter(
        25,
        accepted_values=[
            "Twang",
            "Clav",
            "Xylophone",
            "Slippery Slope",
            "Enharmonic Square",
            "Xylogphone 2",
            "Mellow Square",
            "Chaos 1",
            "Chaos 2",
            "Chaos 3",
            "Chaos 4",
            "Bright Square",
            "Hollow",
            "BP Square",
            "Ski Slope",
            "Rasp",
            "Peal",
            "Fuzz",
            "Floss",
            "Excite",
            "Awaken",
            "Energize",
            "BP Twang",
            "Complex Pulse",
            "Mellow Square 2",
            "Harmonic Square",
            "Thin Ramp",
            "Xylophone 3",
            "Thin Square",
            "Harmonic Ramp",
            "Rouse",
            "Waken",
            "Sine",
            "Sawtooth",
            "Square",
            "Dome 1",
            "Dome 2",
            "Mellow Dome",
            "Dome 3",
            "Dome 4",
            "Rasp1",
            "Rasp 2",
            "Rasp 3",
            "Rasp 4",
            "Dome 5",
            "HP Saw",
            "High BP Saw",
            "High BP Square",
            "Vocal",
            "Squeeze Box",
            "Pulse",
            "Limp Saw",
            "Spark Wave 1",
            "Spark Wave 2",
            "Spark Wave 3",
            "Mid Wave 1",
            "Cacophonous Buzz 1",
            "Mid Buzz 1",
            "Dome 6",
            "Soft Dome 3",
            "Dome 7",
            "Spark Wave 4",
            "Spark Wave 5",
            "Soft Dome 4",
            "Dome 8",
            "Organ",
            "Spark Wave 6",
            "Soft Wave 1",
            "Soft Wave 2",
            "Spark Wave 7",
            "Reed",
            "Soft Wave 3",
            "Soft Wave 4",
            "Saxophone",
            "Soft Wave 5",
            "Trashy Wave 1",
            "Trashy Wave 2",
            "Trashy Wave 3",
            "Trashy Wave 4",
            "Trashy Wave 5",
            "Trashy Wave 6",
            "Jaw Harp 1",
            "Jaw Harp 2",
            "Soft Wave 6",
            "Thin 1",
            "Thin 2",
            "Spark Wave 8",
            "Spark Wave 9",
            "Spark Wave 10",
            "Soft Dome 5",
            "Soft Dome 6",
            "Cacophonous Buzz 2",
            "Thin 3",
            "Spark Wave 11",
            "Soft Dome 7",
            "Soft Wave 7",
            "Sine 2",
            "Sync'd Sine",
            "Thrashy Wave 7",
            "Twingle Pad",
            "Dome 9",
            "Thin 4",
            "Thin 5",
            "Thrashy Wave 8",
            "Thrashy Wave 9",
            "Thrashy Wave 10",
            "Thrashy Wave 11",
            "Thrashy Wave 12",
            "Thrashy Wave 13",
            "Spark Wave 12",
            "Spark Wave 13",
            "Thrashy Wave 14",
            "Thrashy Wave 15",
            "Rainbow",
            "Soft Dome 8",
            "Trashy Wave 16",
            "Soothing 1",
            "Soothing 2",
            "Space Wave",
            "5th Rasp",
            "Octave Wave",
            "Triangle + Overtones",
            "Pulse + Overtones",
            "Rising Square",
            "Soft Wave 8",
            "Cacophonous Buzz 3",
            "Silence",
            "White Noise",
        ],
    )
    voice_B_coarse_tuning = nallely.ModuleParameter(116)
    voice_B_fine_tuning = nallely.ModuleParameter(112)
    voice_C_wave = nallely.ModuleParameter(
        26,
        range=(0, 127),
        accepted_values=[
            "Twang",
            "Clav",
            "Xylophone",
            "Slippery Slope",
            "Enharmonic Square",
            "Xylogphone 2",
            "Mellow Square",
            "Chaos 1",
            "Chaos 2",
            "Chaos 3",
            "Chaos 4",
            "Bright Square",
            "Hollow",
            "BP Square",
            "Ski Slope",
            "Rasp",
            "Peal",
            "Fuzz",
            "Floss",
            "Excite",
            "Awaken",
            "Energize",
            "BP Twang",
            "Complex Pulse",
            "Mellow Square 2",
            "Harmonic Square",
            "Thin Ramp",
            "Xylophone 3",
            "Thin Square",
            "Harmonic Ramp",
            "Rouse",
            "Waken",
            "Sine",
            "Sawtooth",
            "Square",
            "Dome 1",
            "Dome 2",
            "Mellow Dome",
            "Dome 3",
            "Dome 4",
            "Rasp1",
            "Rasp 2",
            "Rasp 3",
            "Rasp 4",
            "Dome 5",
            "HP Saw",
            "High BP Saw",
            "High BP Square",
            "Vocal",
            "Squeeze Box",
            "Pulse",
            "Limp Saw",
            "Spark Wave 1",
            "Spark Wave 2",
            "Spark Wave 3",
            "Mid Wave 1",
            "Cacophonous Buzz 1",
            "Mid Buzz 1",
            "Dome 6",
            "Soft Dome 3",
            "Dome 7",
            "Spark Wave 4",
            "Spark Wave 5",
            "Soft Dome 4",
            "Dome 8",
            "Organ",
            "Spark Wave 6",
            "Soft Wave 1",
            "Soft Wave 2",
            "Spark Wave 7",
            "Reed",
            "Soft Wave 3",
            "Soft Wave 4",
            "Saxophone",
            "Soft Wave 5",
            "Trashy Wave 1",
            "Trashy Wave 2",
            "Trashy Wave 3",
            "Trashy Wave 4",
            "Trashy Wave 5",
            "Trashy Wave 6",
            "Jaw Harp 1",
            "Jaw Harp 2",
            "Soft Wave 6",
            "Thin 1",
            "Thin 2",
            "Spark Wave 8",
            "Spark Wave 9",
            "Spark Wave 10",
            "Soft Dome 5",
            "Soft Dome 6",
            "Cacophonous Buzz 2",
            "Thin 3",
            "Spark Wave 11",
            "Soft Dome 7",
            "Soft Wave 7",
            "Sine 2",
            "Sync'd Sine",
            "Thrashy Wave 7",
            "Twingle Pad",
            "Dome 9",
            "Thin 4",
            "Thin 5",
            "Thrashy Wave 8",
            "Thrashy Wave 9",
            "Thrashy Wave 10",
            "Thrashy Wave 11",
            "Thrashy Wave 12",
            "Thrashy Wave 13",
            "Spark Wave 12",
            "Spark Wave 13",
            "Thrashy Wave 14",
            "Thrashy Wave 15",
            "Rainbow",
            "Soft Dome 8",
            "Trashy Wave 16",
            "Soothing 1",
            "Soothing 2",
            "Space Wave",
            "5th Rasp",
            "Octave Wave",
            "Triangle + Overtones",
            "Pulse + Overtones",
            "Rising Square",
            "Soft Wave 8",
            "Cacophonous Buzz 3",
            "Silence",
            "White Noise",
        ],
    )
    voice_C_coarse_tuning = nallely.ModuleParameter(117)
    voice_C_fine_tuning = nallely.ModuleParameter(113)
    voice_D_wave = nallely.ModuleParameter(
        27,
        accepted_values=[
            "Twang",
            "Clav",
            "Xylophone",
            "Slippery Slope",
            "Enharmonic Square",
            "Xylogphone 2",
            "Mellow Square",
            "Chaos 1",
            "Chaos 2",
            "Chaos 3",
            "Chaos 4",
            "Bright Square",
            "Hollow",
            "BP Square",
            "Ski Slope",
            "Rasp",
            "Peal",
            "Fuzz",
            "Floss",
            "Excite",
            "Awaken",
            "Energize",
            "BP Twang",
            "Complex Pulse",
            "Mellow Square 2",
            "Harmonic Square",
            "Thin Ramp",
            "Xylophone 3",
            "Thin Square",
            "Harmonic Ramp",
            "Rouse",
            "Waken",
            "Sine",
            "Sawtooth",
            "Square",
            "Dome 1",
            "Dome 2",
            "Mellow Dome",
            "Dome 3",
            "Dome 4",
            "Rasp1",
            "Rasp 2",
            "Rasp 3",
            "Rasp 4",
            "Dome 5",
            "HP Saw",
            "High BP Saw",
            "High BP Square",
            "Vocal",
            "Squeeze Box",
            "Pulse",
            "Limp Saw",
            "Spark Wave 1",
            "Spark Wave 2",
            "Spark Wave 3",
            "Mid Wave 1",
            "Cacophonous Buzz 1",
            "Mid Buzz 1",
            "Dome 6",
            "Soft Dome 3",
            "Dome 7",
            "Spark Wave 4",
            "Spark Wave 5",
            "Soft Dome 4",
            "Dome 8",
            "Organ",
            "Spark Wave 6",
            "Soft Wave 1",
            "Soft Wave 2",
            "Spark Wave 7",
            "Reed",
            "Soft Wave 3",
            "Soft Wave 4",
            "Saxophone",
            "Soft Wave 5",
            "Trashy Wave 1",
            "Trashy Wave 2",
            "Trashy Wave 3",
            "Trashy Wave 4",
            "Trashy Wave 5",
            "Trashy Wave 6",
            "Jaw Harp 1",
            "Jaw Harp 2",
            "Soft Wave 6",
            "Thin 1",
            "Thin 2",
            "Spark Wave 8",
            "Spark Wave 9",
            "Spark Wave 10",
            "Soft Dome 5",
            "Soft Dome 6",
            "Cacophonous Buzz 2",
            "Thin 3",
            "Spark Wave 11",
            "Soft Dome 7",
            "Soft Wave 7",
            "Sine 2",
            "Sync'd Sine",
            "Thrashy Wave 7",
            "Twingle Pad",
            "Dome 9",
            "Thin 4",
            "Thin 5",
            "Thrashy Wave 8",
            "Thrashy Wave 9",
            "Thrashy Wave 10",
            "Thrashy Wave 11",
            "Thrashy Wave 12",
            "Thrashy Wave 13",
            "Spark Wave 12",
            "Spark Wave 13",
            "Thrashy Wave 14",
            "Thrashy Wave 15",
            "Rainbow",
            "Soft Dome 8",
            "Trashy Wave 16",
            "Soothing 1",
            "Soothing 2",
            "Space Wave",
            "5th Rasp",
            "Octave Wave",
            "Triangle + Overtones",
            "Pulse + Overtones",
            "Rising Square",
            "Soft Wave 8",
            "Cacophonous Buzz 3",
            "Silence",
            "White Noise",
        ],
    )
    voice_D_coarse_tuning = nallely.ModuleParameter(118)
    voice_D_fine_tuning = nallely.ModuleParameter(114)


class LfoSection(nallely.Module):
    lfo1_shape = nallely.ModuleParameter(54)
    lfo1_rate = nallely.ModuleParameter(72)
    lfo1_amount = nallely.ModuleParameter(70)
    lfo2_shape = nallely.ModuleParameter(55)
    lfo2_rate = nallely.ModuleParameter(73)
    lfo2_amount = nallely.ModuleParameter(28)


class FilSection(nallely.Module):
    amount = nallely.ModuleParameter(47)
    attack = nallely.ModuleParameter(85)
    decay = nallely.ModuleParameter(86)
    sustain = nallely.ModuleParameter(87)
    release = nallely.ModuleParameter(88)


class VcaSection(nallely.Module):
    attack = nallely.ModuleParameter(81)
    decay = nallely.ModuleParameter(82)
    sustain = nallely.ModuleParameter(83)
    release = nallely.ModuleParameter(84)


class VcfSection(nallely.Module):
    cutoff = nallely.ModuleParameter(74)
    resonance = nallely.ModuleParameter(71)


class EffectSection(nallely.Module):
    type = nallely.ModuleParameter(9)
    rate = nallely.ModuleParameter(92)
    depth = nallely.ModuleParameter(91)


class KeysSection(nallely.Module):
    notes = nallely.ModulePadsOrKeys()
    pitchwheel = nallely.ModulePitchwheel()
    modulation = nallely.ModuleParameter(1)
    portamento = nallely.ModuleParameter(5)


class Provsmini(nallely.MidiDevice):
    oscillator: OscillatorSection  # type: ignore
    lfo: LfoSection  # type: ignore
    fil: FilSection  # type: ignore
    vca: VcaSection  # type: ignore
    vcf: VcfSection  # type: ignore
    effect: EffectSection  # type: ignore
    keys: KeysSection  # type: ignore

    def __init__(self, device_name=None, *args, **kwargs):
        super().__init__(
            *args,
            device_name=device_name or "PROVS-MINI",
            **kwargs,
        )

    @property
    def oscillator(self) -> OscillatorSection:
        return self.modules.oscillator

    @property
    def lfo(self) -> LfoSection:
        return self.modules.lfo

    @property
    def fil(self) -> FilSection:
        return self.modules.fil

    @property
    def vca(self) -> VcaSection:
        return self.modules.vca

    @property
    def vcf(self) -> VcfSection:
        return self.modules.vcf

    @property
    def effect(self) -> EffectSection:
        return self.modules.effect

    @property
    def keys(self) -> KeysSection:
        return self.modules.keys
