drschlange:
  lisa:
    general:
      master_volume:
        cc: 7
        description: "General Volume"
        init: 0
      engine_select:
        cc: 8
        description: "Engine Selection"
        init: 0
      sustain:
        cc: 64
        description: "Sustain (Hold notes)"
        init: 0
      midi_dev:
        cc: 127
        description: "Dev functions"
    buttons:
      b1:
        cc: 100
        description: "B1"
        init: 0
      b2:
        cc: 101
        description: "B2"
        init: 0
      b3:
        cc: 102
        description: "B3"
        init: 0
      b4:
        cc: 103
        description: "B4"
        init: 0
      b5:
        cc: 104
        description: "B5"
        init: 0
    envelope:
      attack:
        cc: 11
        description: "Envelope Attack"
        init: 0
      release:
        cc: 12
        description: "Envelope Release"
        init: 0
    filter:
      cutoff:
        cc: 74
        description: "Filter Cutoff"
        init: 0
      resonance:
        cc: 71
        description: "Filter Resonance"
        init: 0
    modulation:
      timbre:
        cc: 9
        description: "Timbre"
        init: 0
      timbre_mod:
        cc: 16
        description: "Timbre Modulation"
        init: 0
      color:
        cc: 10
        description: "Color"
        init: 0
      color_mod:
        cc: 17
        description: "Color Modulation"
        init: 0
      FM_mod:
        cc: 15
        description: "FM Modulation"
        init: 0
    wavetable:
        stream_input: "pitchwheel+stream"
        capture_mode:
          cc: 122
          description: "Selects the type of capture mode"
          accepted_values:
            - forward
            - backward
            - rolling
            - buf-forward-rl
            - buf-backward-lr
            - rolling-backward
        phase_reset:
          cc: 126
          description: "Reset the phase"
        phase_offset:
          cc: 125
          description: "Add an offset to the phase"
        retrigger:
          cc: 124
          description: "Reset the phase on note strike"
          accepted_values:
            - OFF
            - ON
        freeze:
          cc: 123
          description: "Freeze the current wavetables"
          accepted_values:
            - OFF
            - ON
    keys:
      notes: "keys_or_pads"
      pitchwheel: "pitchwheel"
